spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        id.new_generator_mappings: true
        jdbc.time_zone: UTC
    database: postgresql
    open-in-view: false

logging:
  level:
    dev.shashiirk.shopmate: info

app:
  security:
    jwt:
      # Secret is Base64 encoded
      secret: ${JWT_SECRET}
      # Token is valid for 24 hours = 24 * 60  * 60 * 1000
      token-validity-in-milliseconds: 86400000
